version: 2.1

executors:
  android-executor:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m

commands:
  prepare:
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

jobs:
  build:
    executor: android-executor
    steps:
    - prepare
    - run:
        name: Run Tests
        command: ./gradlew lint lintKotlin test
    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_test_results:
        path: app/build/test-results
    - persist_to_workspace:
        root: .
        paths:
        - .

workflows:
  version: 2.1
  build:
    jobs:
    - build
